### ISSUE TITLE
Allow reading AWS credentials from ENV

### ISSUE THREAD

**Issue by Luzifer** [minio/mc#1607]
> As a system administrator managing multiple AWS accounts with certain security requirements I need to have the tools I'm using to be able to access those accounts without pasting the credentials into unencrypted plaintext files on my harddisk.

I'm using a tool to set my environment variables to access those different AWS accounts from an encrypted storage after having to enter a master password. Sure I could add several `s3+accountname` entries to the `~/.mc/config.json` file but that would lead to a plain text file having all the credentials in them. Though they are of limited access I would need to suspect every program / script on my system is able to retrieve them.

If `mc` would retrieve the credentials from ENV I only need to trust the tool storing/setting the ENV variables and `mc`. No other program has access to them as they are stored in the current shells environment.

## Expected

If left out from the configuration file `mc` tries to read the credentials from default AWS environment variables and the actions are executed on their behalf.

## Observed

```bash
# awsenv run private mc ls s3
mc: <ERROR> Unable to stat ‘s3’. XML syntax error on line 164: invalid character entity &ntilde;
INFO[0001] Unclean exit with exit-code != 0

# awsenv run demo env | grep AWS
AWS_ACCESS_KEY_ID=demo-key
AWS_SECRET_ACCESS_KEY=demo-secret
AWS_ACCESS_KEY=demo-key
AWS_SECRET_KEY=demo-secret
AWS_REGION=us-east-1
AWS_DEFAULT_REGION=us-east-1
```

**Comment by vadmeste** [comment]
It seems to me that this scenario is good: writing a small binary which accompanies mc to decrypt the access key using a password, this latter will be asked to be entered, then it will be set in the current  environment and run a child shell (I suppose that $SHELL is always present), in that case, you will be able to run mc many times without entering the password each time, of course more thinking is needed because it is about a security feature!

**Comment by harshavardhana** [comment]
> I'm using a tool to set my environment variables to access those different AWS accounts from an encrypted storage after having to enter a master password. Sure I could add several s3+accountname entries to the ~/.mc/config.json file but that would lead to a plain text file having all the credentials in them. Though they are of limited access I would need to suspect every program / script on my system is able to retrieve them.
> 
> If mc would retrieve the credentials from ENV I only need to trust the tool storing/setting the ENV variables and mc. No other program has access to them as they are stored in the current shells environment.

The reason is that using environment variables is limited in its scope, mc's primary use case is also about being able to transfer data between multiple S3 accounts to multi data centers. There is no way to do this with AWS environment variables, even if we achieve it would be harder for users themselves to handle this on their end. 

We will talk internally and see how it can be addressed.

**Comment by vadmeste** [comment]
This is a ten minutes script which explains how all of this could be done https://gist.github.com/vadmeste/b11f8b7de9a5909d4c87, run it then execute this, ```env | grep MC_``̀`

**Comment by harshavardhana** [comment]
> This is a ten minutes script which explains how all of this could be done https://gist.github.com/vadmeste/b11f8b7de9a5909d4c87, run it then execute this, `env | grep MC_̀`

Nice i see so the decoding logic is inside?

**Comment by vadmeste** [comment]
yes, eventually a new field should be added in config.json to indicate the encryption algorithm. If mc detects that field, it will search the plain key in its environment, if not found, it will be abort immediately, hence the encryption/decryption expertise will be in only one place

**Comment by vadmeste** [comment]
better, mc will always search for the key in the environment first, if not found, search it in config.json, if a encryption algorithm is specified, it will abort. If the user wants to enter the password:
```
$ mcenv mc ls ...
Password: 
```
