### ISSUE TITLE
Support removing deleted files/folders and adding empty folders when using mirror

### ISSUE THREAD

**Issue by F21** [minio/mc#1626]
I am using the minio client and minio server on Windows.

Currently, when I use the mirror command like so `mc mirror C:/Users/someuser/files myminio/somebucket`, it will copy new files over to the server.

However, it doesn't create any empty folders on the server or delete any files on the server that were deleted on the client.

It would be nice if support for these 2 things are added.

**Comment by harshavardhana** [comment]
> However, it doesn't create any empty folders on the server or delete any files on the server that were deleted on the client.

- Empty folders are not created since object storage is a flat namespace, there are no concept of directories. 
- Deleting as such is dangerous, especially when there is an active i/o i.e 'mc mirror'. 

We will circle back and see how non intrusive this can be done but for the time being it is expected that 'mc mirror' will not delete the target contents.

**Comment by harshavardhana** [comment]
Will be fixed in #1628
