### ISSUE TITLE
mc cp does not break on error

### ISSUE THREAD

**Issue by balamurugana** [minio/mc#1737]
When `mc cp -r /usr myminio/mybucket` is run, where `mybucket` does not exist, it does not fail on `NoSuchBucket` error.

```
mc: <ERROR> Failed to copy ‘/usr/bin/grog’. Bucket ‘mybucket’ does not exist.                                                                         
```

It could check bucket existence before preparing copy operation and it could also fail if anyone of cp operation.

mc version
```
Version: 2016-06-04T00:32:38Z
Release-tag: DEVELOPMENT.2016-06-04T00-32-38Z
Commit-id: 475670de7d9b10f4bc0d5d6f25f1a858c32c5628
```

**Comment by harshavardhana** [comment]
> When mc cp -r /usr myminio/mybucket is run, where mybucket does not exist, it does not fail on NoSuchBucket error.
> 
> mc: <ERROR> Failed to copy ‘/usr/bin/grog’. Bucket ‘mybucket’ does not exist.                                                                         
> It could check bucket existence before preparing copy operation and it could also fail if anyone of cp operation.
> 
> mc version

It avoids that since there is no real association of bucket v/s object at top layer. Since the bucket could be a local directory as well and there is no specific check for 'bucket' alone.  What you are seeing is also destination validation not source. 

Destination is not explicitly validated, since on 'fs' there is no need for destination directory to exist since it is created automatically, so it fails later.
