### ISSUE TITLE
ls --incomplete

### ISSUE THREAD

**Issue by limbo127** [minio/mc#1944]
Hello, 
is it possible to indicate, number of parts or original size of file in description of incomplete ls.
{"status":"success","type":"file","lastModified":"2016-12-27T12:11:25+01:00","size":5174722560,"key":"test"}   => osize=15174722560 or  part:5/10  

Regards, 
Nicolas

**Comment by harshavardhana** [comment]
Seems like a good idea.. We can explore on implementing this.

**Comment by harshavardhana** [comment]
> is it possible to indicate, number of parts or original size of file in description of incomplete ls.
> {"status":"success","type":"file","lastModified":"2016-12-27T12:11:25+01:00","size":5174722560,"key":"test"} => osize=15174722560 or part:5/10

Original size is not possible since it could be a stream without a length,  we can provide total parts uploaded

**Comment by limbo127** [comment]
Yes, total parts and total parts uploaded

2017-01-23 0:23 GMT+01:00 Harshavardhana <notifications@github.com>:

**Comment by harshavardhana** [comment]
> Yes, total parts and total parts uploaded

Can you explain a bit more on what is the required value here the issue with providing this information is that we see that its not useful in anyway. 

- We cannot know what are total parts it can happen so that the incoming stream might not provide the size. 
- Total parts uploaded we can provide, but what value does it provide - since usually a user is interested in how much storage is being used by the incomplete multiparts.

Can you elaborate more on the requirement?

**Comment by limbo127** [comment]
Hello,
In fact we need to known percentage of current upload (during the process
of uploading ) .
I think totat parts uploaded is interesting, if we know size of part ?
Regards
Nicolas

2017-01-24 1:09 GMT+01:00 Harshavardhana <notifications@github.com>:

**Comment by harshavardhana** [comment]
> Hello,
> In fact we need to known percentage of current upload (during the process
> of uploading ) .
> I think totat parts uploaded is interesting, if we know size of part ?

We had some internal discussion about this - want to know why this feature is useful? because parts can come in many sizes with in a multipart upload and such a type of information shouldn't be exposed on `mc` 

`mc` is a tool tp provide an abstracted view of FS and Object Storage.  With a functionality like this would make it inconsistent with incomplete filesystem files i.e partially downloaded files. 

You need to ideally use a lower level library for this or directly use minio-go to get this information.

**Comment by limbo127** [comment]
ok, I understand.
