### ISSUE TITLE
Copy performs unnecessary operations, requiring unnecessary permissions

### ISSUE THREAD

**Issue by scottsb** [minio/mc#2044]
## Scenario
`mc cp` from local to cloud

## Expected behaviour
Performs only a `PUT` on the object, thus requiring only `s3:PutObject` permission.

## Actual behaviour
Performs a `GET` of all buckets and then up to 15 repeated `HEAD` calls on the bucket before finally performing the actual `PUT` on the object that was requested. The earlier  `GET` and `HEAD` requests require extra permissions, so if only `s3:PutObject` is granted, then they return 403 and sometimes take up to 500ms each to return. This means a copy of a tiny file ends up taking tens of seconds to perform.

## mc version
mc version 2017-02-06T20:16:19Z

## System information
MacOS 10.10.5

**Comment by harshavardhana** [comment]
> Performs a GET of all buckets and then up to 15 repeated HEAD calls on the destination before finally performing the actual PUT that was requested. This requires more permissions, so if only s3:PutObject is granted, then the earlier GET and HEAD requests return 403, sometimes taking up to 500ms each to return. This means a copy of a tiny file ends up taking tens of seconds to perform.

`mc` cannot only do PutObject()  `mc` uses minio-go library which transparently supports uploading as single PUT or multipart automatically.  `minio-go` also manages location for you appropriately.  Along with this it does input validation etc. 

So a simple `s3:PutObject` as part of IAM or bucket policy is pretty much useless for `mc`.   What you can do is just use `aws-sdk`s and upload the file using `s3Client.PutObject()` using `mc` doesn't add much benefit for your use case.

**Comment by scottsb** [comment]
@harshavardhana, sorry I'm just seeing this now. Notifications from GitHub have a problem getting through to my email for some reason.

My issue is that I don't understand why any of the essential functionality in a copy requires a `GET` or `HEAD`. Using a multi-part or single upload call automatically is useful, but a copy should be a write operation, not a read operation. That's why our security rules boil down to what they do: our use case requires clients to be able to push data but not retrieve it.

We could, of course, use the straight S3 SDK, but our goal for using `mc` was a standard, easily scriptable tool for all our interactions with S3, plus the benefit of being able to switch to minio itself in the future. (I don't know if minio itself supports a write-but-not-read permission model: we haven't investigated that far.) It may still not be a use case you want to support, but it's not quite true that there is no value in using `mc`.

**Comment by harshavardhana** [comment]
> My issue is that I don't understand why any of the essential functionality in a copy requires a GET or HEAD. Using a multi-part or single upload call automatically is useful, but a copy should be a write operation, not a read operation. That's why our security rules boil down to what they do: our use case requires clients to be able to push data but not retrieve it.
> 

```
mc cp --debug /etc/issue s3/vadmeste 2>&1 |grep 'mc: <DEBUG>'
```

A cp operation for example does 5 operations in total 

Operation 1: 
```
mc: <DEBUG> GET /vadmeste/?location= HTTP/1.1
```

This is to fetch location of the bucket since minio-go transparently supports all s3 regions, this is a one time activity doesn't happen for all other subsequent operations. 

Operation 2:
```
mc: <DEBUG> HEAD / HTTP/1.1
mc: <DEBUG> HEAD / HTTP/1.1
mc: <DEBUG> HEAD / HTTP/1.1
```
There are some validation techniques which are used by `mc` itself i.e to check the validity of the bucket, it also in-turn verifies further if the prefix exists since the prefix is empty here it would in-turn would have again verified bucket exists and upload only starts once all this validation is finished. 

```
mc: <DEBUG> PUT /issue HTTP/1.1
```

So removing all this and optimizing doesn't add much value to `mc` - these were implemented to provide a consistent cli behavior starting with throwing proper errors, and not transferring data when it is really not needed etc. 

We can certainly explore optimizing the number of operations here but it is not really a priority for us, since most of our users do not have this requirement. 

So when you saying copy should be just a write operation - `mc` is not an API to API front-end with wrappers on top to provide a CLI that is why i suggested to use aws-sdk because that perfectly fits your use-case.  `mc` uses all APIs available to facilitate abstracted behavior of filesystem to object storage and vice versa. 

> We could, of course, use the straight S3 SDK, but our goal for using mc was a standard, easily scriptable tool for all our interactions with S3, plus the benefit of being able to switch to minio itself in the future. (I don't know if minio itself supports a write-but-not-read permission model: we haven't investigated that far.) It may still not be a use case you want to support, but it's not quite true that there is no value in using mc.

Minio server supports write-but-not-read-permission with bucket policies `mc policy upload <alias>/mybucket`, Minio also supports custom bucket policies i.e you can upload your own policy JSON using aws-sdk's.

**Comment by harshavardhana** [comment]
> 
> mc: <DEBUG> PUT /issue HTTP/1.1

Also NOTE: in a batched operation such as when you are copying a large directory the HEAD operations only happen for the first attempt only - once it is validated that the bucket exists and location is obtained you would see only PUT and POST (multipart) operations going to S3.  So optimizing these 4 API calls is not worth complicating `mc`.

**Comment by scottsb** [comment]
Thanks for the detailed explanation. I understand your reasoning.
