### ISSUE TITLE
Policy change using suffix

### ISSUE THREAD

**Issue by rakesh-eltropy** [minio/mc#2124]
We would like to have support of changing the policy of folders with suffix using minio client.
e.g.  mc policy download /eltropy/viewer-docs/documents/*_files

I would like to change policy of all the folders which ends with _files.

**Comment by harshavardhana** [comment]
The reason this won't work as it is because shell escapes * you can still try using quotes. 

```
$ mc policy download 'play/testbucket/documents/*_files'
Access permission for `play/testbucket/documents/*_files` is set to `download`
$ mc policy list play/testbucket/
testbucket/documents/*_files* => readonly
```

Also the alias is wrong in the `mc policy` command line that you posted - alias doesn't begin with '/'

Either its `mc policy download eltroy/`  or you have configured a different alias `mc config host list` should provide previously configured alias in config file.

You can see the previous command working with suffixes

```
$ mc cp /etc/issue play/testbucket/documents/1_files/
/etc/issue:                26 B / 26 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 485 B/s 0s
$ curl https://play.minio.io:9000/testbucket/documents/files/issue
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Key></Key><BucketName></BucketName><Resource>/testbucket/documents/files/issue</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
$ curl https://play.minio.io:9000/testbucket/documents/1_files/issue
Ubuntu 16.04.2 LTS \n \l
```

**Comment by deekoder** [comment]
Can we close this @rakesh-eltropy if you think this works for you now.

**Comment by rakesh-eltropy** [comment]
Its working as expected. Closing the issue.
