### ISSUE TITLE
Head fails on MacOS

### ISSUE THREAD

**Issue by nl5887** [minio/mc#2137]
## Expected behaviour
mc banner

## Actual behaviour
$ go run main.go
signal: killed

## Steps to reproduce the behaviour
Just checkout minio/mc latest and go run main.go

## mc version
9a881562b93f5fb7af0968ab85282896caa81f9f

## System information
MacOS

Darwin MacBook-Pro.local 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64 i386 MacBookPro13,1 Darwin

Killed is mostly an out of memory error, caused by something recursive. Dee confirmed this issue on her notebook as well.

**Comment by deekoder** [comment]
Yes this is repros for me on my mac as well when i do go get.

**Comment by deekoder** [comment]
```
$ mc --help
Killed: 9
```

**Comment by harshavardhana** [comment]
This is upstream golang bug with xcode 8.3 

https://github.com/golang/go/issues/19734

**Comment by deekoder** [comment]
Ok i installed xcode8.3 and then did this go version
```
go version go1.7.5 darwin/amd64
$ go build -ldflags=-s main.go
$ mc
Killed: 9
```

**Comment by deekoder** [comment]
ok so this works.
```
$ go version 
go1.7.5 darwin/amd64
$ go build -ldflags=-s 
$ ./mc
```

**Comment by badscooter23** [comment]
This is a nasty problem when it comes up... `brew doctor` will encourage you to update to a new version of xcode and then you rung into this issue... 

I am not sure I completely understand your workaround (right now I am just postponing the xcode update to make sure I don't get the problem)...

normally I doe a `make` to build `minio` and/or `mc`... 

Can you be more clear on how to get around the problem? 
Do we need to modify the `Makefile` with different `-ldflags`? Or do we need to not use `make` and do an explicit `go build`? 

I am just unclear on what you are saying the workaround is (and the problem is debilitating if it comes up). 

I think we just need to write up a really clear work around for this... that hopefully 

- works with go 1.7.5 
- works with latest xcode
- allows developer to do a `make` to build `mc`
- doesn't get the `Killed: 9` issue

(I am getting around this be not upgrading `xcode` right now)

**Comment by harshavardhana** [comment]
@badscooter23 `brew install minio/stable/mc` should handle this work-around and also `make`. 

This is an issue that can happen if you did `go get github.com/minio/mc` which is allowed, but there is no way to stop you from doing the latter.

**Comment by deekoder** [comment]
If you do on OSX
```
go get github.com/minio/mc 
```
Then if you do 
```
go install -ldflags "-s"
```
builds the mc binary correctly and I also tested it a bit with ls and cp. Everything works.
