### ISSUE TITLE
Retrieve metadata from objects

### ISSUE THREAD

**Issue by aw** [minio/mc#2251]
## Expected behaviour

Metadata is returned as `X-Amz-Meta-*` HTTP request headers, or as metadata keys in JSON response. Perhaps a new cmdline flag (ex: `mc ls --head mybucket/object.txt`) or in DEBUG output (ex: `mc --debug ls mybucket/object.txt`).

The metadata appears when using the python `awscli` cmdline tool.

## Actual behaviour

User-defined metadata is never returned.

## Steps to reproduce the behaviour

```
mc --json ls mybucket/object.txt`
{"status":"success","type":"file","lastModified":"2017-09-12T03:55:50.209Z","size":86016,"key":"object.txt"}

aws --endpoint-url http://localhost:9000 s3api head-object --bucket mybucket --key object.txt
{
    "AcceptRanges": "bytes", 
    "ContentType": "text/plain; charset=utf-8", 
    "LastModified": "Tue, 12 Sep 2017 03:55:50 GMT", 
    "ContentLength": 86016, 
    "ETag": "\"b181c8c08967f88003bf81b97e07470a\"", 
    "Metadata": {
        "username": "tester", 
        "location": "office", 
        "email": "tester@test.com", 
        "sha256": "1ab503a3f4e48431aba92bc8769b2b3becb4865437b5165990a42b7fbbb2dee5"
    }
}
```

## mc version

```
Version: 2017-09-10T05:49:25Z
Release-tag: DEVELOPMENT.2017-09-10T05-49-25Z
Commit-id: 631f7fc194fe0ad8d26cb16ca264ca6665fcd151
```

## System information

Linux w/kernel 3.16.38 x86_64

EDIT: wrong kernel version

**Comment by poornas** [comment]
@aw, user metadata is returned by the HEAD object call as per the s3 api. The `mc ls` command is equivalent to the `aws ls`  command and not the `aws head-object` call, so this is working as intended.

**Comment by aw** [comment]
Sorry if I wasn't clear. This is a feature request, not a bug. At the moment there is no way to retrieve user metadata through the `mc` utility.

**Comment by poornas** [comment]
@aw, will have to get back to you on this after discussing this internally.

**Comment by harshavardhana** [comment]
> Sorry if I wasn't clear. This is a feature request, not a bug. At the moment there is no way to retrieve user metadata through the mc utility.

Requesting user metadata might be really expensive operation on large buckets are you sure you want this information? because each object requires a HeadObject() call to get the metadata information. 

It is better for you to configure your server to send bucket notifications and update a database/key-value store instead.  Lets say if you are using Minio server you can configure https://docs.minio.io/docs/minio-bucket-notification-guide#Elasticsearch to perhaps replicate your namespace of your entire bucket and query elastic search for these metadata instead.

**Comment by aw** [comment]
@harshavardhana metadata on objects, not on buckets. Please see the example I posted above, the request is to retrieve metadata for one specific object only.

I also suggested a new flag for `mc ls` such as `--head`.

**Comment by harshavardhana** [comment]
I understand what you mean wholly. I want to suggest a better alternative for you to look at object metadata through populating your namespace to a query friendly backend. This can be achieved by using the previously referenced documentation.

This option is not useful for `mc` and will be seldomly used IMO. You need to provide a stronger use case otherwise we prefer to avoid adding rarely used options.

**Comment by aw** [comment]
@harshavardhana thanks for the explanation.

I'm considering your suggestion as I write this :smile: If the metadata is being accessed programmatically, there's definitely more power and flexibility from having the object metadata stored externally. It's something I will look into (likely MQTT or Redis).

S3 object metadata is probably **the** most important feature of self-hosted object storage, so i'm sure many people would appreciate at least being able to retrieve it (even if only for testing).

Since the `--debug` flag is a _seldomly_ used feature, perhaps it would make sense to include user metadata when specifying `--debug` ? What do you think?

**Comment by harshavardhana** [comment]
We decided to implement this as a new sub command such as `mc stat` which has variations like `mc stat --recursive` which can pretty much give you the metadata information about each objects. 

This issue is not blocked anymore.
