### ISSUE TITLE
Allow to set default region into mc config

### ISSUE THREAD

**Issue by cernyjakub** [minio/mc#2371]
## Expected behaviour

`mc` should be able to store default region in its config. We use local minio cluster with `eu-central` region setting and we have to specify `--region "eu-central"` parameter to all commands.

## Actual behaviour

No way to put default region into JSON config file. 

## mc version

Version: 2017-12-12T01:08:02Z
Release-tag: RELEASE.2017-12-12T01-08-02Z
Commit-id: `4cb6e3534286819d3e11db7c3659164655020bd3`

**Comment by harshavardhana** [comment]
You don't need to set any region for Minio - if you need to be default @cernyjakub . We cannot do a default region because it conflicts with AWS S3 behavior and there is no real reason why this would be needed in the first place.

--region is only required for `mc mb` no other commands need this information, since every other command gets region information automatically from the server by using GetBucketLocation API.

Now if you want it to be default you can simply create an alias on your end i.e

```
alias makebucket='mc mb --region eu-central-1' 
```

**Comment by nitisht** [comment]
@cernyjakub closing this as answered, feel free to reopen if you have other question.
