### ISSUE TITLE
mc does not support AWS temporary access tokens

### ISSUE THREAD

**Issue by TJC** [minio/mc#2444]
## Expected behaviour

This works fine if you *are not* using session tokens, but if you are, it fails because mc doesn't have a place to accept the session token.

```
~$ env | grep AWS
AWS_SECRET_ACCESS_KEY=Fxxxxxxxxxxxxxxx8
AWS_DEFAULT_REGION=us-east-1
AWS_SESSION_TOKEN=XxxxxxxxxY
AWS_ACCESS_KEY_ID=AxxxxxxxxxxxxxxxQ
~$ aws s3 ls
# .. s3 output follows, successfully ..

~$ mc config host add s3 https://s3.amazonaws.com \
    $AWS_ACCESS_KEY_ID \
    $AWS_SECRET_ACCESS_KEY

~$ mc ls s3
mc: <ERROR> Unable to list folder. The AWS Access Key Id you provided does not exist in our records.

~$ mc version
Version: 2017-10-14T00:51:16Z
Release-tag: RELEASE.2017-10-14T00-51-16Z
Commit-id: 785e14a725357b39e22b74483cd202e7effa6195
```

**Comment by harshavardhana** [comment]
Yep we need to support this.. we only currently support long term keys.

**Comment by deekoder** [comment]
@TJC we will plan on this for the future.

**Comment by deekoder** [comment]
We will close this and mark it future. Will reopen when we are done with current priorities.

**Comment by fcomte** [comment]
Will you support this feature?

**Comment by varkey** [comment]
@deekoder Has there been any progress on this? Would be really good to have support for temporary AWS credentials.

**Comment by harshavardhana** [comment]
Unfortunately no @varkey

**Comment by olevitt** [comment]
Hello,

I would love this feature for our organisation.  
Any chance to have any progress on this ?
Would you accept PR for this if I submit one (not sure if I can handle it yet) ?

Thanks !

**Comment by harshavardhana** [comment]
Sure feel free to submit a PR currently we don't see working on this feature

**Comment by subdavis** [comment]
I'm not sure why maintainers haven't mentioned this, but `mc` does support temporary session tokens if you're willing to edit `~/.mc/config.json` directly.  The data model supports it, there's just no way to set the token through the command line.

You could even generate a temporary file and load it with `mc --config-dir` if you needed to script it.

Here's my config file, works just fine.

``` json
{
	"version": "10",
	"aliases": {
		"local": {
			"url": "http://localhost:9000",
			"accessKey": "CHANGE",
			"secretKey": "CHANGE",
			"sessionToken": "CHANGE",
			"api": "s3v4",
			"path": "auto"
		}
	}
}
```

**Comment by harshavardhana** [comment]
> ## workaround
> I'm not sure why maintainers haven't mentioned this, but `mc` does support temporary session tokens if you're willing to edit `~/.mc/config.json` directly. The data model supports it, there's just no way to set the token through the command line.
> 
> I went poking around to see how hard it would be to add and found that it already existed in [configV10](https://github.com/minio/mc/blob/90dc31f6ba4be6a78e25ba244756f90c1d943b6f/cmd/config-v10.go#L39-L46)
> 
> You could even generate a temporary file and load it with `mc --config-dir` if you needed to script it.
> 
> Here's my config file, works just fine.
> 
> ```json
> {
> 	"version": "10",
> 	"aliases": {
> 		"local": {
> 			"url": "http://localhost:9000",
> 			"accessKey": "CHANGE",
> 			"secretKey": "CHANGE",
> 			"sessionToken": "CHANGE",
> 			"api": "s3v4",
> 			"path": "auto"
> 		}
> 	}
> }
> ```

No need to modify the config, that is not recommend we do mention it openly in the docs.

https://github.com/minio/mc/blob/master/docs/minio-client-complete-guide.md#specify-temporary-host-configuration-through-environment-variable

I don't know if you happen to read this documentation.

**Comment by rrossouw01** [comment]
In case someone finds this useful.  In some environments I have to use Windows so here is a powershell example to update the minio client config.  I also had a version just setting a variable MC_HOST instead.  I think I prefer updating the config because setting an environment variable is an extra copy/paste step (at least in linux/mac it is).
`
function aws_get_token ($AWS_PROFILE) {
  $AWS_REGION="us-west-2"
  $Working_path = "$HOME\.aws\sso\cache"
  
  $file_json = @(Get-ChildItem $Working_Path\* -exclude "*boto*.json")
  $CACHE_FILE = $file_json[0]
  $CACHE_TOKEN=$(cat ${CACHE_FILE} | .\jq.exe -r '.accessToken')
  $SSO_ACCOUNT_ID=$(aws configure get sso_account_id --profile ${AWS_PROFILE})
  $SSO_ROLE_NAME=$(aws configure get sso_role_name --profile ${AWS_PROFILE})
 
  $SSO_TEMP_CREDS=$(aws --profile $AWS_PROFILE sso get-role-credentials --account-id $SSO_ACCOUNT_ID --role-name $SSO_ROLE_NAME --access-token $CACHE_TOKEN --region $AWS_REGION)
  $AWS_ACCESS_KEY_ID=$(echo $SSO_TEMP_CREDS | .\jq.exe -r '.roleCredentials.accessKeyId')
  $AWS_SECRET_ACCESS_KEY=$(echo $SSO_TEMP_CREDS | .\jq.exe -r '.roleCredentials.secretAccessKey')
  $AWS_SESSION_TOKEN=$(echo $SSO_TEMP_CREDS | .\jq.exe -r '.roleCredentials.sessionToken')
  
  $MINIO_CONFIG="C:\Users\VENRROSSOUW\mc\config.json"
  $fileContent = ConvertFrom-Json "$(Get-Content $MINIO_CONFIG -Encoding Ascii)"
  $fileContent.aliases.${SSO_ACCOUNT_ID}.accessKey = ${AWS_ACCESS_KEY_ID}
  $fileContent.aliases.${SSO_ACCOUNT_ID}.secretKey = ${AWS_SECRET_ACCESS_KEY}
  $fileContent.aliases.${SSO_ACCOUNT_ID}.sessionToken = ${AWS_SESSION_TOKEN}
  $fileContent | ConvertTo-Json -Depth 100 | Out-File $MINIO_CONFIG -Encoding Ascii
}

Write-Host "-------------------------------------`r`n------AWS MFA Minio Client Config Token Updater------`r`n-------------------------------------`r`n`r`nTo use this your AWS account must have a valid AWS Access Key`r`nAND an Active MFA Authentication method on your AWS account`r`n`r`n"

$PROFILE=$args[0]
aws_get_token $PROFILE`

**Comment by MartinLoeper** [comment]
new link to the docs for reference: https://min.io/docs/minio/linux/reference/minio-mc/minio-client-settings.html#envvar.MC_HOST_-ALIAS

`export MC_HOST_<alias>=https://<Access Key>:<Secret Key>:<Session Token>@<YOUR-S3-ENDPOINT>`
