### ISSUE TITLE
Handle ls command with backslash as separator (git bash)

### ISSUE THREAD

**Issue by jmayday** [minio/mc#2484]
## Expected behaviour
As a user I expect to get descriptive message telling me that 
```
mc ls host\bucket
```
is not a correct command as slash should be used (I use git bash)
This is really misleading as if I try to execute any of the commands like
```
mc ls notdefinedhost\existingbucket
mc ls definedhost\nonexistingbucket
mc ls notdefinedhost\nonexistingbucket
```
I get nice message "<ERROR> Unable to stat `notdefinedhostexistingbucket`. Request file notdefinedhostexistingbucket` not found". I know that something is wrong with command. 

## Actual behaviour
Actual behavior is that if I specify existing host and existing bucket but use backslash as separator I get not error and nothing from bucket is listed so I have impression my bucket is empty. 

## Steps to reproduce the behaviour
Execute command 
```
mc ls host\bucket
```

under git bash specyfing correct host and existing bucket

## mc version
VERSION:
  2018-06-30T00:13:31Z

## System information
Windows 10

**Comment by harshavardhana** [comment]
Can you reproduce this issue without using `git bash` instead using powershell or cmd ?

**Comment by kannappanr** [comment]
@jmayday You will not be able to reproduce this issue in Windows using powershell and cmd. As far as `git bash` is concerned, it behaves like `Linux` shell and in the case of `Linux` , `\` is an escape character and bash will just skip that character. 

Because of this `mc` sees this as `hostbucket` instead of a bucket named `bucket` inside an S3 alias names `host`. In your case, since you do not have an alias named `hostbucket`, it tries the operation on the local file system and it fails.

If you are using `git bash`, you will to use `mc ls host/bucket` for the command to work.

I believe `git bash` is working as intended.

**Comment by jmayday** [comment]
Thank you for your replies and clarification. I thought it might be useful to provide even a hint (about host-bucket separator) if mc has been invoked using git bash. But maybe I just overrated level of confusion here ;)

**Comment by kannappanr** [comment]
@jmayday This is a bash behavior, when `mc` receives the argument, it will already have been stripped of `\`.
