### ISSUE TITLE
Change --insecure flag to --skipcertcheck

### ISSUE THREAD

**Issue by kannappanr** [minio/mc#2542]
*** Not using standard template ***

`mc` currently uses `--insecureflag` flag for the case where self signed certificates are used. The name is a little misleading. So, this needs to be changed to `--skipcertcheck`

**Comment by aead** [comment]
For completeness:
Using the go TLS config option `InsecureSkipVerify` will cause mc to
 - ignore any mismatch between the certificate hostname (subject) and the S3 endpoint domain name
 - ignore the certificate chain -> It's not necessary that the presented certificate is part of a chain ending at a RootCA certificate.
 - use the current local time to check whether the certificate is expired

So the S3 server can present **any** certificate with a valid expiry time (w.r.t. the client's local time).
This needn't to be necessary a self-signed certificate but can also be another valid certificate e.g. the certificate delivered by `google.com`.
So from a technical perspective `--selfsigned` is not completely correct. However, the new flag also be understandable by users

**Comment by aead** [comment]
I want to propose a semantic change to `mc` TLS certificate handling:

Instead of skipping the TLS certificate checks `mc` could handle self-signed certificates similar to ssh public keys.
SSH presents the public key hash to the users on the first connection and asks the user to accept or reject the connection based on the public key hash. Once the user accepts the connection (permanently) the public key hash is added to the ssh-agent.

Similarly `mc` could reject any TLS connection if the certificate is not signed by a trusted root CA.
With the `--self-signed` flag `mc` computes the public key hash (and compares it to the cert pub key hash) and presents it to the users. The user then can accept or reject the connection. If the user accepts the connection the public key hash is added to `mc` config file (see later). For any future request `mc` compares the public key hash of the certificate to the stored public key hash and only accepts the connection if they match. The `--self-signed` flag wouldn't be required for any subsequent requests.
**This would give the `mc` user the same experience as SSH.**

The `mc` config for a given S3 endpoint would change the following (assuming `play` would have a self-signed certificate):
```
"play": {
			"url": "https://play.minio.io:9000",
			"accessKey": "Q3AM3UQ867SPQQA43P2F",
			"secretKey": "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG",
			"api": "S3v4",
			"lookup": "auto",       
                        "certKeyHash:"sha256:CFCE3F2AD474BD3EA2FD12DEFD274A628D69E3A368C315281CF7D8A4347B9370",
},
```
On the first connection (TOFU - trust on first use) `mc` adds the hash to the config file if the user accepts the public key hash on the command line.

**Comment by kannappanr** [comment]
@aead I checked with AB and we will change the flag to --self-signed. As far as hash part is concerned, he suggested, we can add it as part of adding an mc config, that way you do not have to enter it even once.

**Comment by aead** [comment]
@kannappanr Yeah, my idea was that `mc --self-signed` shows the public key hash **on first access** in case of **self signed cert**. Once the user confirms (`y/n`) mc adds the hash to the mc config file such that `--self-signed` is needn't to be specified anymore. It would really be like the SSH experience. If you connect to an "unknown" server SSH will show you the key fingerprint (hash) and ask you to confirm. From that point on you "know" the key and you can connect without any further actions...

**Comment by kannappanr** [comment]
closing this issue, as we will be using issues https://github.com/minio/mc/issues/2596 and https://github.com/minio/minio/issues/6801 instead.
