### ISSUE TITLE
mc does not recognize csv in windows correctly

### ISSUE THREAD

**Issue by deekoder** [minio/mc#2559]
## Expected behavior

Right now, MIME type for a CSV file while using with mc select shows xls. We have to use our own MIME type library to reliably get the correct content type for csv objects across platforms.

## Actual behavior
Using a CSV object from windows does not work correctly with mc select SQL feature since the content type is not showing csv.

## Steps to reproduce the behavior
Upload CSV object from a windows computer and see if s3 select works on Linux mc

## Proposed solution
Update the pkg/mime-db package in our own codebase. Update the MIME DB info in our own package, re-vendorize this and test if the correct type is detected.
## mc version
- (paste output of `mc version`)

**Comment by Praveenrajmani** [comment]
Here we use go's native package `mime` for identifying the content-type from extension. It resolves `.xls` files to `application/vnd.ms-excel` which is why mc does not support select query for such objects.

I think we should not generalize the meaning of `mime.resolveFromExtension` function of any mime pkg (either ours `pkg/mime-db` or `mime` pkg of go) . There are `xls` files that may not contain comma-separated values (excel native files). Since we only need the particular xls-->csv resolution for the `select` feature, it is enough if we allowed such xls files by treating them as csv and relaxing the content-type checks in the `mc select` here. 

By `.xls` types we mean `.csv` files which are probably renamed as `.xls` right ? Neither minio nor s3 will support xls parsing for Select.

**Comment by harshavardhana** [comment]
> Here we use go's native package `mime` for identifying the content-type from extension. It resolves `.xls` files to `application/vnd.ms-excel` which is why mc does not support select query for such objects.
> 
> I think we should not generalize the meaning of `mime.resolveFromExtension` function of any mime pkg (either ours `pkg/mime-db` or `mime` pkg of go) . There are `xls` files that may not contain comma-separated values (excel native files). Since we only need the particular xls-->csv resolution for the `select` feature, it is enough if we allowed such xls files by treating them as csv and relaxing the content-type checks in the `mc select` here.
> 
> By `.xls` types we mean `.csv` files which are probably renamed as `.xls` right ? Neither minio nor s3 will support xls parsing for Select.

All you have to do is simply move from Go native package `mime` to `minio/minio/pkg/mimedb` which will always give you `csv --> text/csv` , xls is not supported in select API so we don't need to worry about it.
