### ISSUE TITLE
Implement mc admin health command

### ISSUE THREAD

**Issue by nitisht** [minio/mc#2606]
**Not using template on purpose**

Often we see users facing issues in their distributed environment - one or more nodes may have 

- Less free memory 
- High cpu usage 
- Slow drives 
- Network connectivity issues

It is difficult to debug these problems easily - the tools to identify these issues are different and it needs multiple steps before the actual problem is identified. It will be helpful if we bring subset of these tools under one umbrella to help users identify problems on their distributed Minio deployments. 

Based on discussion with @abperiasamy , we will have a `mc admin health` command that will check and report

- cpu usage
- network (between client and each remote node)
- memory usage
- drive performance (equivalent to `dd` uncached)

for each remote node that is a part of a single Minio distributed deployment. After this, as next steps we can bring internode network stats. 

Also ref: https://github.com/minio/minio/issues/6159 for context.

**Comment by wlan0** [comment]
Had a conversation with @abperiasamy about this earlier this week. He proposed the following changes
- The command should be called `stat` Instead of `perf`, since `stat` is the accurate term for the information we’re providing in this feature.
- Provide historical Disk latency and Disk throughput, instead of writing to disk when the command is called
- Provide historical and current Internode network latency and throughput
- Provide historical and current average of CPU load and Mem usage 

Here’s my Implementation plan:
- Implement the current average of CPU load and Mem usage
- Implement the current latency and throughput of internode network communication
- Implement the changes to disk stats

Some more notes:
- semantics of `mc admin` commands: 
   * `mc admin hw` - show hardware information - CPU ID, Mem details, Net interface details, Disk details (incorporating @harshavardhana’s solution described here: 
https://github.com/minio/minio/pull/7038#issuecomment-451590590) 
   * `mc admin info` - server info - HTTP stat information
   * `mc admin stat` - net/cpu/mem/disk statistics shown by this feature

**Comment by harshavardhana** [comment]
This has been implemented now as `mc admin obd`
