### ISSUE TITLE
[Bug] mc accepts only printable characters as encryption keys on the command line

### ISSUE THREAD

**Issue by donatello** [minio/mc#2678]
## Expected behavior

The key should be encoded (to base64) on the command line.

## Actual behavior

The following form cannot be used when the key has non-printables:

```
mc cp --recursive \
    --encrypt-key "s3/documents/=32byteslongsecretkeymustbegiven1,myminio/documents/=32byteslongsecretkeymustbegiven2" \
    s3/documents/ myminio/documents/
```

**Comment by sinhaashish** [comment]
@donatello  Can you help me in reproducing this? I mean how do you pass a non printable character in encryption key. Sorry , it might be lame question but i couldn't find a soln.

**Comment by donatello** [comment]
@sinhaashish The encryption key can be any sequence of 32 bytes. Since mc requires no encoding on the key, only printable characters can be passed as the key to mc. This is the problem - all possible enc keys cannot be input to mc. To allow all possible encryption keys the user needs base64 encode the key so we get a printable representation to pass on the cli to mc. Then mc needs to decode it to retrieve the raw enc key. Even aws CLI does this.

**Comment by nreynis** [comment]
The scope of this problem is not limited to the mc client, the web service has the same flaw.
`X-Amz-Server-Side-Encryption-Customer-Key` does not support base64 encoding despite the [documentation](https://docs.min.io/docs/how-to-use-minio-s-server-side-encryption-with-aws-cli.html) stating the contrary.

What is even weirder it's that the `X-Amz-Server-Side-Encryption-Customer-Key-MD5` header does support base64 correctly.

This is a really important issue because it reduce key entropy from 32 bits to 12 bits. This is weak and insecure.

**Comment by harshavardhana** [comment]
This is incorrect @nreynis server is behaving correctly. It is a current limitation in `mc` it doesn't take non-printable characters as input. 

```
~ aws --profile play --endpoint-url https://play.minio.io:9000 s3api put-object --bucket my-bucket --key my-secret-diary   --sse-customer-algorithm AES256   --sse-customer-key MzJieXRlc2xvbmdzZWNyZXRrZXltdXN0cHJvdmlkZWQ=   --sse-customer-key-md5 7PpPLAK26ONlVUGOWlusfg==  --body /etc/hosts
{
    "SSECustomerKeyMD5": "7PpPLAK26ONlVUGOWlusfg==", 
    "SSECustomerAlgorithm": "AES256", 
    "ETag": "\"43bdfb597eea4376c6169178afc21caa\""
}
```

**Comment by nreynis** [comment]
You are right everything is fine on minio server side. My HTTP request was malformed due to my incomprehension of how the AWS SDK handled the values.

Back on the initial issue: is there any way of properly passing the raw bytes to the minio/mc client ? or are we limited to ASCII printable characters for now ?

**Comment by harshavardhana** [comment]
It is limited to printable characters which is the gist of the issue which needs to be fixed.
