### ISSUE TITLE
unsolicited console interaction "Install mc auto-completion in your shell ?"

### ISSUE THREAD

**Issue by vadim-v-p** [minio/mc#2816]
(I rename execitable to mcli because I use midnight-commander a lot)
REPRO:
curl -sSLo /usr/bin/mcli https://dl.minio.io/client/mc/release/linux-amd64/mc
chmod +x /usr/bin/mcli
EXPECTED:
can use mcli in scripts
CURENT:
it always goes interactive
mcli
mcli: Configuration written to `/root/.mc/config.json`. Please update your access credentials.
mcli: Successfully created `/root/.mc/share`.
mcli: Initialized share uploads `/root/.mc/share/uploads.json` file.
mcli: Initialized share downloads `/root/.mc/share/downloads.json` file.
Install mc auto-completion in your shell ? (y/n):

**Comment by harshavardhana** [comment]
Issue transferred to relevant repo.

**Comment by sritimmaraju** [comment]
I am facing the same error in one of our concourse jobs, is there a workaround for this scenario
```
Setting minio host...
mc: Configuration written to `/root/.mc/config.json`. Please update your access credentials.
mc: Successfully created `/root/.mc/share`.
mc: Initialized share uploads `/root/.mc/share/uploads.json` file.
mc: Initialized share downloads `/root/.mc/share/downloads.json` file.
Install mc auto-completion in your shell ? (y/n): 
```

**Comment by vadmeste** [comment]
`--no-autocompletion` flag is needed to avoid that prompt

**Comment by harshavardhana** [comment]
mc shouldn't prompt if it's run as a script in non terminal environment @vadmeste - not sure why @vadim-v-p is seeing this in their scripts.

**Comment by vadmeste** [comment]
@harshavardhana actually there is no clear way to check if a program is running in a script or not.

When mc is executed in a script, mc is still connected to a real terminal, which I guess inherited from the shell.

I did some investigation, currently there is a environment variable called SHLVL which means shell level, it is not so reliable mechanism but I didn't find other way until now.

**Comment by harshavardhana** [comment]
If there is no tty attached I think it is clearly possible, this is the way we detect coloring or non coloring environments. The os.system() call doesn't give access to the tty so it is surprising that it's not possible.

**Comment by vadmeste** [comment]
The drawback of SHLVL is that users using tmux or screen won't be to see the prompt because it is always shell level 2

**Comment by y0ssar1an** [comment]
I think this should be given a higher priority. This prompt breaks the use of `mc` in scripts. That's gotta be the most common usage of `mc`.

**Comment by tjtelan** [comment]
With respect, I don't care for this new prompt. 👎 

It is very unexpected, and it is interrupting my CI builds because you've incorrectly identified how I am using `mc`. You're trying to assume how I'm using `mc` it in order to upsell auto-completions?

The introduction of this prompt is causing my CI builds to fail because `mc` holds up my script execution until it times out. I would rather not modify all my scripts to expect this to sometimes be interactive. I urge you to re-think using this pattern in the future, please.

My opinion: 
I want auto-completions. I just wish I were introduced in a less careless manner. I would rather install auto-completion manually through a subcommand, instead of worry about future prompts in my scripts.

**Comment by abperiasamy** [comment]
Let's remove automatic auto-completion setup and replace --no-autocompletion with --autocomplete enable shell autocompletion feature.

**Comment by abperiasamy** [comment]
@vadim-v-p we will also make mc use config dir in the name of the binary.
