### ISSUE TITLE
Add support for a `tail` command (or a reverse `mc head`)

### ISSUE THREAD

**Issue by ricardbejarano** [minio/mc#2837]
I'd like to see something similar to *NIX's `tail(1)`, which prints the last few lines of a file to stdout.

If adding another command to `mc` is not ideal, this feature could be added to `mc head` with some flag like `-r, --reverse`, `-t, --tail` or by supporting negative integer values in the `-n value, --lines value` flag.

I could submit a PR if this feature is approved.

**Comment by harshavardhana** [comment]
The problem is downloading large objects here @ricardbejarano - while it is possible to add.  The tail has the problem of download all the object and then being able to skip a lot of bytes. So it can be quite a lot time-consuming. It may not be a worthwhile command to add. 

It is easier to do head because all you have to do is read-only first few lines.

**Comment by ricardbejarano** [comment]
Sure, `mc` would have to pull the entire object as (AFAIK) you can't pull a file from it's end (which is a great feature Amazon could add to S3, BTW), but the alternative would be to `mc cp` the file and running `tail` locally, which sort of detriments the "modern alternative to UNIX commands" point of `mc`.

I would add it for completeness, if there's a `head` there should be a `tail`.

What do you think? @harshavardhana

**Comment by harshavardhana** [comment]
The head is there because it's easy to do as a performant CLI, a tail wouldn't be easy to consume from a user point of view. We wouldn't want to add just because there are Unix alternatives for it we have to see if they are practically usable. 

The problem is `tail` like commands are not useful because the object sizes on object storage are too big.

**Comment by ricardbejarano** [comment]
I understand.

I guess we'll wait until S3 and other object storage solutions support "bottoms-up" `GetObject` operations.
