### ISSUE TITLE
FR - --remove option for source

### ISSUE THREAD

**Issue by eco-minio** [minio/mc#2953]
Not using template on purpose

We allow for --remove option on target but not on source.  Use case is, I want all items in a bucket older than 30 days to be moved to s3, then have those objects deleted after successful copy.  This can be accomplished today via something like 

` mc mirror --older-than 29d myminio/mybucket s3/mybucket &&  mc find myminio/mybucket --older-than30d --exec "mc rm {} myminio/mybucket`

but looking for a cleaner solution that doesn't risk data loss when mirror does not finish in a day, for example.

Attention: @kannappanr

**Comment by harshavardhana** [comment]
The reason we don't delete this on source is because source is assumed as pristine copy and deletes shouldn't be triggered by client operation on source.

Implementation of this option may make it incompatible and prone to data loss like issues if not carefully used. It is better to use lifecycle policies on source instead of relying on mc mirror IMHO

**Comment by ebozduman** [comment]
@eco-minio: ping!

Do you agree with @harshavardhana 's comment?

Please close the issue if you agree. Otherwise, make your point and explain why we need yet another "remove" option, this time for the source file.

Please either let me know or call for a short meeting with AB to decide what we can do about this feature request.

**Comment by eco-minio** [comment]
@harshavardhana is there a cleaner solution?  That still requires setting up two things (lcm and mirror), If not we can close this.

**Comment by harshavardhana** [comment]
We agreed that this will be server-side lifecycle configuration not part of mirror, closing this issue.
