### ISSUE TITLE
Support for mc mv

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/mc#3077]
A customer requested `mc mv` command such that as it copies the files it removes from the source so that disk space is conserved. Downside of breaking it into `mc cp` followed by `mc rm` is that it would need double the disk usage (since `mc rm` runs only after `mc cp` finishes)

**Comment by kannappanr** [comment]
Just adding the requirements here

1. Will not work for source/target buckets with lock enabled
2. otherwise, this should be similar to `mc cp`
--recursive, -r copy recursively
--older-than value copy objects older than L days, M hours and N minutes
--newer-than value copy objects newer than L days, M hours and N minutes
--storage-class value, --sc value set storage class for new object(s) on target
--encrypt value encrypt/decrypt objects (using server-side encryption with server managed keys)
--attr value add custom metadata for the object
--continue, -c create or resume copy session
--preserve, -a preserve filesystem attributes (mode, ownership, timestamps)
--encrypt-key value encrypt/decrypt objects (using server-side encryption with customer provided keys)
--config-dir value, -C value path to configuration folder (default: "/home/kannappan/.mc")
--quiet, -q disable progress bar display
--no-color disable color theme
--json enable JSON formatted output
--debug enable debug output
--insecure disable SSL certificate verification
--help, -h show help
instead of sending single object delete after every successful put on the destination, we need to save the list of objects copied and then remove it. Otherwise it will lbe very chatty for small objects. The list can be for every 1000 objects deleted, we can send one `DeleteObjects` API. This is just a suggestion, please investigate the issue there etc.
