### ISSUE TITLE
cp does multiple getobjects when the source is S3

### ISSUE THREAD

**Issue by kannappanr** [minio/mc#3170]
## Expected behavior
Just do one getobject to download one object
## Actual behavior
Does two getobject calls

## Steps to reproduce the behavior

issue `mc cp myminio/test/issue /tmp`
monitor `mc admin trace myminio`
You can see that more than one `getobject` call is issued

## mc --version
RELEASE.2020-04-15T20-18-00Z

**Comment by klauspost** [comment]
Dupe of #3149  - the test case is the same, at least.

**Comment by vadmeste** [comment]
My finding:

mc issues two GET requests but it only downloads few bytes in the first call. Also, it only happens when the content-type of the source object is unknown (application/octet-stream). So mc is actually passing the first 512 bytes to a magic library to recognize the file type from its contents.
