### ISSUE TITLE
mc can not parse S3:AuthType and s3:SignatureVersion

### ISSUE THREAD

**Issue by DAGorchakov** [minio/mc#3682]
## Actual behavior
[root@gda ~]# mc admin policy add minio/ test /root/test.json
mc: <ERROR> Unable to parse the input policy: invalid condition key 'S3AuthType'.
Connected https://github.com/minio/minio/pull/11947

policy example:
```json
{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Sid": "Deny presigned URL requests.",
			"Action": "s3:*",
			"Effect": "Deny",
			"Principal": "*",
			"Resource": "arn:aws:s3:::*",
			"Condition": {
				"StringNotEquals": {
					"S3:authtype": "REST-HEADER"
				}
			}
		}
	]
}
```

## mc --version
- mc version RELEASE.2021-03-23T05-46-11Z

**Comment by harshavardhana** [comment]
mc is not get updated will be updated soon.

**Comment by ebozduman** [comment]
@DAGorchakov,

@harshavardhana's fix, minio/minio#11947, is good. 

The problem is; your key names are not correct/have typos.
"**S**3:auth**t**ype" is supposed to be "**s**3:auth**T**ype"

and the other key that appears in the title;
"s3:**S**ignature**V**ersion" is supposed to be "s3:**s**ignature**v**ersion"

Please check the documentation, [Amazon S3 Signature Version 4 Authentication Specific Policy Keys](https://docs.aws.amazon.com/AmazonS3/latest/API/bucket-policy-s3-sigv4-conditions.html)

You also need to upgrade to the latest MinIO release. The fix is first shipped with the [April 4th, 2021 release](https://github.com/minio/minio/tree/RELEASE.2021-04-06T23-11-00Z.hotfix).

**Comment by DAGorchakov** [comment]
[root@gda ~]# date
Wed Apr 21 14:16:57 MSK 2021
[root@gda ~]# mc --version
mc version RELEASE.2021-03-23T05-46-11Z
[root@gda ~]# minio --version
minio version RELEASE.2021-04-18T19-26-29Z
[root@gda ~]# cat ~/test.json
{
        "Version": "2012-10-17",
        "Statement": [
                {
                        "Sid": "Deny presigned URL requests.",
                        "Action": "s3:*",
                        "Effect": "Deny",
                        "Principal": "*",
                        "Resource": "arn:aws:s3:::*",
                        "Condition": {
                            "StringNotEquals": {
                            "S3:authType": "REST-HEADER"
                            }
                    }
                },
                {
                        "Sid" : "Allow everything",
                        "Action": "s3:*",
                        "Effect": "Allow",
                        "Resource": "arn:aws:s3:::*"
                }
        ]
}
[root@gda ~]# mc admin policy add gda/ test /root/test.json
mc: <ERROR> Unable to parse the input policy: invalid condition key 'S3:authType'.

**Comment by ebozduman** [comment]
@DAGorchakov,

That is correct. 
And the good news is a new [mc](https://dl.minio.io/client/mc/release/linux-amd64/mc) release is available today.
You can try it out, but make sure you use the correct key names in your policy JSON file.

I still see a typo in the `test.json` file you've copy/pasted in your last comment:

> [root@gda ~]# mc admin policy add gda/ test /root/test.json
mc: <ERROR> Unable to parse the input policy: invalid condition key 'S3:authType'.

'S3:authType' is  supposed to be 's3:authType'.

**Comment by DAGorchakov** [comment]
@ebozduman  Thank you so much, it is fine now!
