### ISSUE TITLE
loss of data when mirroring to replication set 

### ISSUE THREAD

**Issue by roeelavi** [minio/mc#3775]
## Expected behavior: i tried configuring a new minio replica set (which is implemented in two sites and will act as a DR) and transfer all of the data from the old stand alone server to the new server
Final result:
old-bucket: Used: 312.68 GB
new-bucket: Used: 312.68 GB
new-bucket-replica: Used: 312.68 GB
## Actual behavior  
old-bucket: Used: 312.68 GB
new-bucket: Used 23 GB
new-bucket-replica: 15 GB
## Steps to reproduce the behavior
mc version node1/new-bucket
mc version node2/new-bucket-replica
mc admin bucket remote add node1/new-bucket http://ACCESSKEY:SECRETKEY@node2/new-bucket-replica --service "replication" --sync
mc replicate add node1/new-bucket  --arn ARN --remote-bucket "new-bucket-replica" --replicate "existing-objects,delete-marker,delete" --priority 1
mc mirror oldnode/old-bucket node1/new-bucket
## mc --version mc version RELEASE.2021-06-13T17-48-22Z
- (paste output of `mc --version`)

## System information

**Comment by klauspost** [comment]
Just to help debugging:

1) How have you confirmed that MinIO considers itself "finished"?
2) How did you confirm the amount of data transferred?

**Comment by roeelavi** [comment]
the mirroring task stopped 
and i just checked on the web UI

**Comment by klauspost** [comment]
UI numbers may lag real world usage. Scanning the new data will take some time.

You can re-start the mirror. Nothing bad should happen. Check for errors on the mc output.

**Comment by harshavardhana** [comment]
> mc version node1/new-bucket
> mc version node2/new-bucket-replica
> mc admin bucket remote add node1/new-bucket http://ACCESSKEY:SECRETKEY@node2/new-bucket-replica --service "replication" --sync
> mc replicate add node1/new-bucket --arn ARN --remote-bucket "new-bucket-replica" --replicate "existing-objects,delete-marker,delete" --priority 1
> mc mirror oldnode/old-bucket node1/new-bucket

Once mirroring is set why are you doing `mc mirror`?

**Comment by klauspost** [comment]
You are doing `oldnode` (mc mirror) -> `node1` (server-side replication) ->  `node2`, correct?

So manual mirroring from an old node into a cluster that does serverside replication to a third node?

**Comment by roeelavi** [comment]
> > mc version node1/new-bucket
> > mc version node2/new-bucket-replica
> > mc admin bucket remote add node1/new-bucket http://ACCESSKEY:SECRETKEY@node2/new-bucket-replica --service "replication" --sync
> > mc replicate add node1/new-bucket --arn ARN --remote-bucket "new-bucket-replica" --replicate "existing-objects,delete-marker,delete" --priority 1
> > mc mirror oldnode/old-bucket node1/new-bucket
> 
> Once replication is setup on server side - why are you doing `mc mirror`?

im using mc mirror to copy the data from the old server to the new replication set

**Comment by roeelavi** [comment]
> You are doing `oldnode` (mc mirror) -> `node1` (server-side replication) -> `node2`, correct?
> 
> So manual mirroring from an old node into a cluster that does serverside replication to a third node?

yes its correct!

**Comment by poornas** [comment]
@roeelavi , you will be able to `mc mirror` from old cluster to new-bucket if you don't have versioning on the `old-bucket` or versioning enabled with just one version per object. `mc mirror` will only mirror latest version of the object as it does not know about versioning. The low usage on new-bucket indicates one of several possibilities - usage calculation is behind, replication is lagging  OR you have multiple versions of objects in the old-cluster that were not picked up by mirroring.

If usage is lagging, you can tweak scanner speed with `mc admin config set alias scanner` and reduce the delay and max_wait from defaults. If you find object versions on `new-bucket` in `PENDING` replication status, you may also want to bump up replication workers with `mc admin config set alias api` - changing these settings may cause load spike, and you can revert back to original setting if that is the case.

if old-bucket is versioned with multiple versions in the bucket, you will need multi site replication rather than mirroring to achieve this - it is an upcoming feature.

**Comment by klauspost** [comment]
Closing.
