### ISSUE TITLE
--enc-c :  Encryption key should be 44 bytes raw base64 encoded key

### ISSUE THREAD

**Issue by udf2457** [minio/mc#4960]
## Expected behavior

Able to upload

## Actual behavior

> mc: <ERROR> SSE Error. Encryption key should be 44 bytes raw base64 encoded key.The plain text key was 0 bytes but should be 32 bytes long.

## Steps to reproduce the behavior

Bash script similar to following 

```sh
#!/usr/bin/env bash
set -uo pipefail

EXOSCALE_SSE_C_KEY=$(openssl rand -base64 32) # in my environment this contains the actual value
EXOSCALE_GVA_BUCKET=$(openssl rand -hex 8) # in my environment this contains the actual value
MC_HOST_EXOSCALEGVA="https://<Access Key>:<Secret Key>@https://sos-ch-gva-2.exo.io"
TMPFIL=$(mktemp)

mc cp "${TMPFIL}" EXOSCALEGVA/${EXOSCALE_GVA_BUCKET}/ --enc-c "EXOSCALEGVA/${EXOSCALE_GVA_BUCKET}/=${EXOSCALE_SSE_C_KEY}"
```

N.B. I have also tried removing the variables from `--enc-c` and entering actual text values.  The resulting error message from `mc` is the same.

## mc --version
mc version RELEASE.2024-06-10T16-44-15Z (commit-id=7a0a8f54d901fe3ee7b8854347025f54ce3ebbfc)

## System information
Debian Bookworm

**Comment by klauspost** [comment]
This is due to padding.

```
$ openssl rand -base64 32
Cx/ojcSLdVDmmR4J0ORZqNWUkg+5PqLV2NDo1MD9qgk=
```

@zveinn This is pretty hostile, as most base64 implementations add padding. Could you make it accept both? 

```
func main() {
	b, err := base64.StdEncoding.DecodeString("Cx/ojcSLdVDmmR4J0ORZqNWUkg+5PqLV2NDo1MD9qgk=")
	fmt.Println(len(b), err)
}

> 32 <nil>
```

Hex would be nice, but I can live without.

**Comment by udf2457** [comment]
Thanks @klauspost , I'll re-try unpadded !

I agree, it is hostile and would be nice to accept both.

I guess an additional option could be to add `--genkey` which will spit out an unpadded key ?

**Comment by zveinn** [comment]
We can not support the presence of the = character in encryption keys due to the fact they are also valid characters in bucket and object names. 

When we are extracting the key from the --enc-c flag we need to be 100% sure that we are extracting the right key. If we assume things, we might encrypt data with the wrong value. Which can cause users to loose data. 

In the case of a padding, we could assume that if the = character is the last character in the --enc-c flag, then it must be padding. However, if the user simply forgot to enter the key or made a script which did not inject the key we might end up using the object/bucket name as the key because they might also be generated using the same encoding. 

Fow now, the keys need to be `raw std encoding`. However, I will add support for hex keys.

**Comment by zveinn** [comment]
https://github.com/minio/mc/pull/4962

a PR has been made with support for Hex encoding.
